const obj ={
    cart:[
        {
            "name":"kumar",
            "brand":"nike",
            "price":56,
            "qty":1,
            "category":"nike",
            "image":"hiosahoihaos",
            "_id":"1"
        },
        {
            "name":"jai",
            "brand":"addidas",
            "price":62,
            "qty":2,
            "category":"Adidas",
            "image":"hiosahoihaos",
            "_id":"2"
        },
        {
            "name":"priya",
            "brand":"lakme",
            "price":162,
            "qty":3,
            "category":"lakme",
            "image":"hiosahoihaos",
            "_id":"3"
        },
        {
            "name":"veer",
            "brand":"samsung",
            "price":42,
            "qty":3,
            "category":"samsung",
            "image":"hiosahoihaos",
            "_id":"4/"
        }
        ],
    shippingAddress:{
        address:"a/43 shalimar",
        city:"delhi",
        postalCode:"110088",
        country:"india"
    },
    paymentMethod:{
        payment:"paypal",
        paymentResult:{
            id:{type:String},
            status:{type:String},
            update_time:{type:String},
            email_address:{type:String}
        },
        taxPrice:"29.50",
        shippingPrice:"90.40",
        totalPrice:"1220",
        isPaid:"false",
        paidAt:"10 oct,2023",
        isDelivered:"true",
        deliveredAt:"12 oct, 2023"
    }
}