[
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Grow Bag",
    "category": "Bag",
    "brand": "ICONIC",
    "countInStock": 4,
    "price": 790,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "image": "https://th.bing.com/th/id/OIP.kL5NWIog1c5lXGRirCFZLwHaJP?w=157&h=197&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    "description": "Organic vogue 350 gsm home garden,terrace, kitchen gardening,terrace poly house gardening & roof top balcony gardening round grow bag, green white tarpaulin fabric, (PACK OF 4) Grow Bag"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Herbal Cloth Mask",
    "brand": "VIEN",
    "category": "Bag",
    "countInStock": 4,
    "price": 50,
    "discount": 4,
    "gst": 1,
    "totalPrice": 48,
    "description": "CONTARE Premium Polyester Adjustable Ear loops Reusable, Washable, Water Resistant Cloth Mask  (Black, M, Pack of 4, 2 Ply)",
    "image": "https://m.media-amazon.com/images/I/41XjWk23FWL._UX679_.jpg"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Cotton Blend Trousers",
    "category": "Bag",
    "brand": "clothes",
    "countInStock": 4,
    "price": 500,
    "discount": 6,
    "gst": 2,
    "totalPrice": 480,
    "description": "Men Slim Fit Blue Cotton Blend Trousers",
    "image": "https://contents.mediadecathlon.com/p1786946/9f46afdfe2a4d66ba76e148ec9fe6caf/p1786946.jpg?format=auto&quality=70&f=650x0"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "SAMSUNG Galaxy F13",
    "category": "Bag",
    "brand": "SAMSUNG Galaxy",
    "countInStock": 4,
    "price": 15343,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)  (4 GB RAM)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/i/v/-original-imagfhu6bdzhnmkz.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "vivo T2 5G",
    "category": "Bag",
    "brand": "vivo",
    "countInStock": 4,
    "price": 14366,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "vivo T2 5G (Nitro Blaze, 128 GB)  (6 GB RAM)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/i/v/-original-imagfhu6bdzhnmkz.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "NIVIA Storm Football",
    "category": "Bag",
    "brand": "NIVIA",
    "countInStock": 4,
    "price": 700,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "NIVIA Storm Football - Size: 5  (Pack of 1, White)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/ball/6/8/d/300-storm-football-size-5-5-20-1-1-football-nivia-original-imaggurhz3jukjd3.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "PHILIPS BT3101/15 Trimmer",
    "category": "Bag",
    "brand": "PHILIPS",
    "countInStock": 4,
    "price": 999,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "PHILIPS BT3101/15 Trimmer 45 min Runtime 10 Length Settings  (Black, White)",
    "image": "https://rukminim2.flixcart.com/image/416/416/kuof5ow0/trimmer/7/z/f/0-5-10-mm-bt3101-15-stainless-steel-cordless-philips-original-imag7r4r7ztgnuyk.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Running Shoes",
    "category": "Bag",
    "brand": "Bruton",
    "countInStock": 4,
    "price": 999,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Trendy Sports Running Running Shoes For Men  (Black)",
    "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/o/v/e/6-rng-512-black-40-bruton-black-original-imagexnpgzqzzbze-bb.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Nib Fountain Pen",
    "category": "Bag",
    "brand": "Parker",
    "countInStock": 4,
    "price": 463,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "PARKER Vector Gold- Fine Nib Fountain Pen",
    "image": "https://rukminim2.flixcart.com/image/416/416/kbdz5ow0/pen/g/2/p/parker-9000014375-9000014375-original-imafsqxhyykagp3k.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Diary A5 Size",
    "category": "Bag",
    "brand": "ESCAPER",
    "countInStock": 4,
    "price": 359,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "ESCAPER Black Hard Bound Diary A5 Size (200 Pages - PU Leather Cover)| Notebook Ruled A5 A5 Diary Ruled 200 Pages  (Black)",
    "image": "https://rukminim2.flixcart.com/image/416/416/kz1lle80/diary-notebook/u/c/j/black-hard-bound-diary-a5-size-200-pages-pu-leather-cover-original-imagb53m4uyzkgzz.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Diary A5 Size",
    "category": "Bag",
    "brand": "BLUEBERRY ",
    "countInStock": 4,
    "price": 4740,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "BLUEBERRY B-40EQ-GL Builtin Equalizer Electric Semi-acoustic Guitar Basswood Rosewood Right Hand Orientation  (Vintage Sunburst)",
    "image": "https://rukminim2.flixcart.com/image/416/416/kwwfte80/acoustic-guitar/d/p/4/b-40eq-gl-builtin-equalizer-electric-blueberry-original-imag9haknbjqtmgw.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Syska LED Bulb  (White)",
    "category": "Bag",
    "brand": "Syska 9 W Standard B22 LED Bulb  (White) ",
    "countInStock": 4,
    "price": 105,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Syska 9 W Standard B22 LED Bulb  (White)",
    "image": "https://rukminim2.flixcart.com/image/416/416/kx3l0nk0/bulb/p/a/g/1-9w-b22-led-bulb-syska-original-imag9mx4kzhgxnen.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "ASUS Vivobook Pro",
    "category": "Bag",
    "brand": "ASUS",
    "countInStock": 4,
    "price": 74990,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "ASUS Vivobook Pro 15 For Creator, Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 3050/144 Hz) M6500QC-HN741WS Gaming Laptop  (15.6 Inch, Quiet Blue, 1.8 Kg, With MS Office)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/d/k/k/-original-imagqkqnb2fpbhyb.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Men Leather Wallet",
    "category": "Bag",
    "brand": "PROVOGUE ",
    "countInStock": 4,
    "price": 249,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Men Trendy, Travel, Evening/Party, Ethnic, Casual, Formal Blue Artificial Leather Wallet  (5 Card Slots)",
    "category": "Bag", 
    "image": ""
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Sunglasses",
    "category": "Bag",
    "brand": "Optimity ",
    "countInStock": 4,
    "price": 899,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "UV Protection Retro Square Sunglasses (Free Size)  (For Men & Women, Clear)",
    "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shopsy-sunglass/r/w/2/free-size-new-fancy-sunglass-for-men-women-3136-h8-style-guru-original-imagpybdn3wzukeu.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Watch",
    "category": "Bag",
    "brand": "Fastrack ",
    "countInStock": 4,
    "price": 3636,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Fastrack All Nighters Analog Watch - For Men NN3165NL01",
    "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/n/m/g/-original-imagz3zg3xmqhr2z.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Sports/Regular Cap",
    "category": "Bag",
    "brand": "Welim",
    "countInStock": 4,
    "price": 200,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Self Design Sports/Regular Cap",
    "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/cap/q/t/z/m-newsty-combo-cap-aspx-original-imaghyr52qj4zgzb.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Protein Shaker Bottle",
    "category": "Bag",
    "brand": "Welim",
    "countInStock": 4,
    "price": 179,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "MUSCLEBLAZE Compact Shaker, Protein Shaker Bottle, Gym Shaker, 100% Leakproof 500 ml Shaker  (Pack of 1, Black, Plastic)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/bottle/q/j/e/500-compact-shaker-protein-shaker-bottle-gym-shaker-100-original-imagm8chgzh9dhhd.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "American Tourister Large Check-in Suitcase",
    "category": "Bag",
    "brand": "American Tourister",
    "countInStock": 4,
    "price": 2699,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "American Tourister Large Check-in Suitcase (78 cm) - Kam Triprism Aqua Spinner - Blue",
    "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/suitcase/w/y/4/-original-imagmvdh2vetfhah.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Tripod Floor lamp",
    "category": "Bag",
    "brand": "Crosscut ",
    "countInStock": 4,
    "price": 1499,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Crosscut Furniture Tripod Floor lamp",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/floor-lamp/z/5/a/52-mp3-1-crosscut-furniture-original-imagkd9ffgydy6xz.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Xtenshion Crafts Wooden Wall Mount",
    "category": "Bag",
    "brand": "Xtenshion",
    "countInStock": 4,
    "price": 254,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Xtenshion Crafts Wooden Wall Mount Tv Set Up Box Stand Wall Shelves Wooden Wall Shelf  (Number of Shelves - 2, Black)",
    "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/floor-lamp/z/5/a/52-mp3-1-crosscut-furniture-original-imagkd9ffgydy6xz.jpeg?q=70"
  },
  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Analog Wall Clock",
    "category": "Bag",
    "brand": "AJANTA",
    "countInStock": 4,
    "price": 275,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "AJANTA Analog 20.5 cm X 20.5 cm Wall Clock  (Blue, With Glass, Standard)",
    "image": "https://rukminim2.flixcart.com/image/416/416/wall-clock/f/z/t/2147-ajanta-analog-2147-blue-original-imaejmg59sqwgmvs.jpeg?q=70"
  },

  {
    "User": "64a26434296c59d1a9ee9b0f",
    "name": "Natural Perfume",
    "category": "Bag",
    "brand": "Adiveda ",
    "countInStock": 4,
    "price": 279,
    "discount": 4,
    "gst": 1,
    "totalPrice": 766,
    "description": "Adiveda Natural Perfume Trial Pack For women Set Of 5 -12ml each Eau de Parfum - 12 ml  (For Women)",
    "image": "https://rukminim2.flixcart.com/image/416/416/kmthz0w0/perfume/m/d/1/12-perfume-trial-pack-for-women-set-of-5-eau-de-parfum-adiveda-original-imagfmb6h5uwngaw.jpeg?q=70"
  }
]
